sonar.projectKey=Expensese-tracker
sonar.projectName=Expenses-tracker

sonar.java.binaries=target/classes

# 🚫 Exclude runtime / non-source directories
sonar.exclusions=\
mysql-data/**,\
**/mysql-data/**,\
**/*.sql,\
**/*.md,\
screenshots/**,\
target/**

